### ISSUE TITLE
Emulator fails to compile with "not declared in this scope" errors

### ISSUE THREAD

**Issue by achow101** [keepkey/keepkey-firmware#298] opened 2021-08-28 02:56 UTC
When trying to build the emulator on a linux, I get the following errors:

```
/home/andy/bitcoin/keepkey-firmware/tools/emulator/main.cpp: In function ‘void sigintHandler(int)’:
/home/andy/bitcoin/keepkey-firmware/tools/emulator/main.cpp:62:3: error: ‘printf’ was not declared in this scope
   62 |   printf("Quitting...\n");
      |   ^~~~~~
/home/andy/bitcoin/keepkey-firmware/tools/emulator/main.cpp:40:1: note: ‘printf’ is defined in header ‘<cstdio>’; did you forget to ‘#include <cstdio>’?
   39 | #include <signal.h>
  +++ |+#include <cstdio>
   40 | 
/home/andy/bitcoin/keepkey-firmware/tools/emulator/main.cpp:63:10: error: ‘stdout’ was not declared in this scope
   63 |   fflush(stdout);
      |          ^~~~~~
/home/andy/bitcoin/keepkey-firmware/tools/emulator/main.cpp:63:10: note: ‘stdout’ is defined in header ‘<cstdio>’; did you forget to ‘#include <cstdio>’?
/home/andy/bitcoin/keepkey-firmware/tools/emulator/main.cpp:63:3: error: ‘fflush’ was not declared in this scope
   63 |   fflush(stdout);
      |   ^~~~~~
In file included from /home/andy/bitcoin/keepkey-firmware/tools/emulator/main.cpp:29:
/home/andy/bitcoin/keepkey-firmware/tools/emulator/main.cpp: In function ‘int main()’:
/home/andy/bitcoin/keepkey-firmware/include/keepkey/board/keepkey_usart.h:40:5: error: ‘printf’ was not declared in this scope
   40 |     printf(FMT, ##__VA_ARGS__); \
      |     ^~~~~~
/home/andy/bitcoin/keepkey-firmware/tools/emulator/main.cpp:75:3: note: in expansion of macro ‘dbg_print’
   75 |   dbg_print("Application Version %d.%d.%d\n", MAJOR_VERSION, MINOR_VERSION,
      |   ^~~~~~~~~
/home/andy/bitcoin/keepkey-firmware/include/keepkey/board/keepkey_usart.h:40:5: note: ‘printf’ is defined in header ‘<cstdio>’; did you forget to ‘#include <cstdio>’?
   40 |     printf(FMT, ##__VA_ARGS__); \
      |     ^~~~~~
/home/andy/bitcoin/keepkey-firmware/tools/emulator/main.cpp:75:3: note: in expansion of macro ‘dbg_print’
   75 |   dbg_print("Application Version %d.%d.%d\n", MAJOR_VERSION, MINOR_VERSION,
      |   ^~~~~~~~~
```

I did build the dockerfiles, and it seems like there might be some differences between musl and glibc that are at the root of the issue?

**Comment by mrnerdhair** [comment] 2022-03-16 23:18
I haven't been able to reproduce this issue myself. It looks like you're trying to run the non-dockerized build here; if so, I expect the issue is less with libc differences and more with header import paths. (These are POSIX standard utils and are supported by every libc.)

I'll close this for now due to staleness -- which is an us problem, not a you problem -- but feel free to reopen it if you're still having the issue and want a hand.

**Closed by mrnerdhair** 2022-03-16 23:18 UTC
